export const AVAILABLE_COLUMNS = [
  'product category',
  'target',
  'similar',
  'cause',
  'solution',
  'process',
  'from customer',
  'version',
  'functionId',
  'bug type',
  'severity',
  'testCaseId',
  'purpose',
  'department',
  'duplicate issue',
  'tested ok',
  'qna related',
  'difficulty',
  'test on staging ok',
  'defect origin',
  'qc activity',
  'defect type',
  'cause category',
  'main pic',
  'reviewer',
  'defect author',
  'release date',
  'merge to cr',
  'customer',
  'expected revenue ($)',
  '% success',
  'sale',
  'why not find out?',
  'next due date',
  'next action',
  'builded',
  'current state',
  'test checklist',
  'reproduce?',
  'after refactor',
  'swat',
  'test environment',
  'late release',
  'release note',
  'dev_ self tested ok?',
  'contract type',
  'project line',
  'business domain',
  'technology',
  'project size (mm)',
  'team size (mm)',
  'is degrade?',
  'cause (lost/closed/pending)',
  'new customer?',
  'reopen count',
  'new customer info',
  'customer type',
  'pic os',
  'đánh giá của am',
  'đánh giá của os',
  'market',
  'certainty',
  "opp's type",
  'service offering',
  'release ok',
];

export const SELECTED_COLUMNS = [
  '#',
  'Status',
  'Priority',
  'Tracker',
  'Subject',
  'Assignee',
  'Updated',
  'author',
];

export const SORT_ORDER = {
  INCREASE: 'increase',
  DECREASE: 'decrease',
};

export const HEADER_TABLE_ISSUE = {
  INIT: '#',
  STATUS: 'Status',
  PRIORITY: 'Priority',
  TRACKER: 'Tracker',
  SUBJECT: 'Subject',
  ASSIGNEE: 'Assignee',
  UPDATED: 'Updated',
  AUTHOR: 'author',
};
