import type { Metadata } from 'next';
import localFont from 'next/font/local';
import './globals.css';
import { ReduxProvider } from './providers/ReduxProvider';

import ClientSideLayout from './ClientSideLayout';
import Footer from '~/components/layout/Footer';
import Header from '~/components/layout/Header';

const geistSans = localFont({
  src: '../assets/fonts/GeistVF.woff',
  variable: '--font-geist-sans',
  weight: '100 900',
});
const geistMono = localFont({
  src: '../assets/fonts/GeistMonoVF.woff',
  variable: '--font-geist-mono',
  weight: '100 900',
});

export const metadata: Metadata = {
  title: 'NTQ Redmine',
  description: 'Generated by NTQ Redmine',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <ReduxProvider>
          <div className="mx-3 min-w-max w-[calc(100%-24px)]">
            <Header title="hi" />
            <ClientSideLayout>{children}</ClientSideLayout>
            <Footer />
          </div>
        </ReduxProvider>
      </body>
    </html>
  );
}
