import store from '~/store/store';
import type { Metadata } from 'next';
import localFont from 'next/font/local';
import { Provider } from 'react-redux';
import Footer from './components/Footer';
import Header from './components/Header';
import './globals.css';
import { ReduxProvider } from './providers/ReduxProvider';
import SubMain from './components/SubMain/SubMain';
import { useIsProjectPath } from '~/utils/useIsProjectPath';

const geistSans = localFont({
  src: './fonts/GeistVF.woff',
  variable: '--font-geist-sans',
  weight: '100 900',
});
const geistMono = localFont({
  src: './fonts/GeistMonoVF.woff',
  variable: '--font-geist-mono',
  weight: '100 900',
});

export const metadata: Metadata = {
  title: 'NTQ Redmine',
  description: 'Generated by NTQ Redmine',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const excludedPaths = [
    '/projects/fresher-_-reactjs-fresher/files',
    '/projects/fresher-_-reactjs-fresher/settings',
    '/projects/fresher-_-reactjs-fresher/newissue',
    '/projects/fresher-_-reactjs-fresher/new_versions',
  ];

  const isProjectPath = useIsProjectPath(excludedPaths);
  console.log(isProjectPath);

  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <ReduxProvider>
          <div className="mx-3 min-w-max w-[calc(100%-24px)]">
            <Header title="hi" />
            <div className="flex justify-between mt-2">
              <main
                className={`${isProjectPath ? 'w-3/4' : 'w-full'} p-2  border-1 border-solid border-primary-border bg-white h-full min-h-615`}
              >
                {children}
              </main>
              {isProjectPath && 'hi'}
            </div>
            <Footer />
          </div>
        </ReduxProvider>
      </body>
    </html>
  );
}
