// Const SpentTimeDetail
export const AVAILABLE_COLUMNS = [
  'product category',
  'target',
  'similar',
  'cause',
  'solution',
  'process',
  'from customer',
  'version',
  'functionId',
  'bug type',
  'severity',
  'testCaseId',
  'purpose',
  'department',
  'duplicate issue',
  'tested ok',
  'qna related',
  'difficulty',
  'test on staging ok',
  'defect origin',
  'qc activity',
  'defect type',
  'cause category',
  'main pic',
  'reviewer',
  'defect author',
  'release date',
  'merge to cr',
  'customer',
  'expected revenue ($)',
  '% success',
  'sale',
  'why not find out?',
  'next due date',
  'next action',
  'builded',
  'current state',
  'test checklist',
  'reproduce?',
  'after refactor',
  'swat',
  'test environment',
  'late release',
  'release note',
  'dev_ self tested ok?',
  'contract type',
  'project line',
  'business domain',
  'technology',
  'project size (mm)',
  'team size (mm)',
  'is degrade?',
  'cause (lost/closed/pending)',
  'new customer?',
  'reopen count',
  'new customer info',
  'customer type',
  'pic os',
  'đánh giá của am',
  'đánh giá của os',
  'market',
  'certainty',
  "opp's type",
  'service offering',
  'release ok',
];

export const SELECTED_COLUMNS = [
  'Project',
  'Date',
  'User',
  'Activity',
  'Issues',
  'Comment',
  'Hours',
];

export const OPTIONS_DATE = [
  { value: 'any', label: 'any' },
  { value: 'is', label: 'is' },
  { value: '<=', label: '<=' },
  { value: '>=', label: '>=' },
  { value: 'between', label: 'between' },
  { value: 'lessday', label: 'less than days ago' },
  { value: 'moreday', label: 'more than days ago' },
  { value: 'past', label: 'in the past' },
  { value: 'daysago', label: 'days ago' },
  { value: 'today', label: 'today' },
  { value: 'yesterday', label: 'yesterday' },
  { value: 'thisweek', label: 'this week' },
  { value: 'lastwweek', label: 'last week' },
  { value: 'last2week', label: 'last 2 weeks' },
  { value: 'thismonth', label: 'this month' },
  { value: 'lastmhont', label: 'last month' },
  { value: 'thisyear', label: 'this year' },
  { value: 'none', label: 'none' },
];

export const OPTIONS_USER_1 = [
  { value: 'is', label: 'is' },
  { value: 'not', label: 'is not' },
  { value: 'none', label: 'none' },
  { value: 'any', label: 'any' },
];

export const OPTIONS_USER_2 = [
  { value: 'me', label: '<<me>>' },
  { value: 'ducnm', label: 'Duc (Internship) Nguyen Minh' },
  { value: 'ducnv', label: 'Duc 2 (Internship) Nguyen Van' },
  { value: 'dungna', label: 'Dung Nguyen An  (Internship)' },
  { value: 'dungnv', label: 'Dung Nguyen Van 6  (Internship)' },
  { value: 'hainn', label: 'Hai Nguyen Ngoc 1  (Internship)' },
  { value: 'hunglv', label: 'Hung Le Van  (NSD.SDC6)' },
  { value: 'Dunnh', label: 'Huy Dung  (Internship)' },
  { value: 'khanhvd', label: 'Khanh Vu Duy' },
  { value: 'quyetnv', label: 'Quyet Nguyen Van  (Internship)' },
  { value: 'sonnhh', label: 'Son (internship) Nguyen Hoang Huu' },
  { value: 'thanhpv', label: 'Thanh Pham Van 1  (NJP.NJP.DLD)' },
  { value: 'vietnv', label: 'Viet (Internship) Nguyen Van' },
];

export const OPTIONS_FILTER = [
  { value: 'date', label: 'Date' },
  { value: 'user', label: 'User' },
  { value: 'activity', label: 'Activity' },
  { value: 'comment', label: 'Comment' },
  { value: 'hours', label: 'Hours' },
  { value: 'productcategory', label: 'Product Category' },
  { value: 'market', label: "Issue's Market" },
  { value: 'target', label: "Issue's Target" },
  { value: 'degrade', label: "Issue's Degrade" },
  { value: 'contract', label: "Issue's Contract Type" },
  { value: 'similar', label: "Issue's Similar" },
  { value: 'cause', label: "Issue's Cause" },
  { value: 'solution', label: "Issue's Solution" },
  { value: 'process', label: "Issue's Process" },
  { value: 'customer', label: "Issue's From Customer" },
  { value: 'version', label: "Issue's Version" },
  { value: 'functionid', label: "Issue's FunctionID" },
  { value: 'Bug Type', label: "Issue's Bug Type" },
  { value: 'Severity', label: "Issue's Severity" },
  { value: 'Department', label: "Issue's Department" },
  { value: 'Duplicate', label: "Issue's Duplicate issue" },
  { value: 'Tested', label: "Issue's Tested OK" },
  { value: 'QnA', label: "Issue's QnA Related" },
  { value: 'difficulty', label: "Issue's Difficulty" },
  { value: 'testonstaging', label: "Issue's Test on staging OK" },
  { value: 'defectorigin', label: "Issue's Defect Origin" },
  { value: 'QCActivity', label: "Issue's QC Activity" },
  { value: 'defecttype', label: "Issue's Defect Type" },
  { value: 'causecategory', label: "Issue's Cause Category" },
  { value: 'customer', label: "Issue's Customer" },
  { value: 'mainPIC', label: "Issue's Main PIC" },
  { value: 'sale', label: "Issue's Sale" },
  { value: 'reviewer', label: "Issue's Reviewer" },
  { value: 'defectauthor', label: "Issue's Defect Author" },
  { value: 'releasedate', label: "Issue's Release Date" },
  { value: 'mergetoCR', label: "Issue's Merge to CR" },
  { value: '%Success', label: "Issue's % Success" },
  { value: 'expectedrevenue', label: "Issue's Expected Revenue ($)" },
  { value: 'currentstate', label: "Issue's Current State" },
  { value: 'nextaction', label: "Issue's Next Action" },
  { value: 'nextduedate', label: "Issue's Next Due Date" },
  { value: 'builded', label: "Issue's Builded" },
  { value: 'testchecklist', label: "Issue's Test checklist" },
  { value: 'reproduce', label: "Issue's Reproduce?" },
  { value: 'afterrefactor', label: "Issue's After Refactor " },
  { value: 'swat', label: "Issue's Swat " },
  { value: 'testenvironment', label: "Issue's Test Environment" },
  { value: 'laterelease', label: "Issue's Late Release " },
  { value: 'releasenote', label: "Issue's Release Note" },
  { value: 'projectline', label: "Issue's Project Line" },
  { value: 'businessdomain', label: "Issue's Business Domain" },
  { value: 'technology', label: "Issue's Technology" },
  { value: 'project Size ', label: "Issue's Project Size (MM)" },
  { value: 'teamsize(MM)', label: "Issue's Team size (MM)" },
  { value: 'degrade?', label: "Issue's Is Degrade?" },
  { value: 'reopencounter', label: "Issue's Reopen counter" },
  { value: 'newcustomer?', label: "Issue's New customer?" },
  { value: 'customertype', label: "Issue's Customer Type" },
  { value: 'pic', label: "Issue's PIC OS" },
  { value: 'rrelease', label: "Issue's Release OK " },
];

export const OPTIONS_TIME = [
  { value: 'year', label: 'Year', hidden: true },
  { value: 'month', label: 'Month' },
  { value: 'week', label: 'Week' },
  { value: 'days', label: 'Days' },
];

export const OPTIONS_ADD = [
  { value: 'project', label: 'Project' },
  { value: 'status', label: 'Status' },
  { value: 'version', label: 'Version' },
  { value: 'category', label: 'Category' },
];

export const SORT_ORDER = {
  INCREASE: 'increase',
  DECREASE: 'decrease',
};

export const HEADERS = {
  DATE: 'Date',
  PROJECT: 'Project',
  USER: 'User',
  ACTIVITY: 'Activity',
  ISSUES: 'Issues',
  COMMENT: 'Comment',
  HOURS: 'Hours',
};

export const IMAGE_ALTS = {
  CHECK: 'Check',
  SORT_UP: 'Sort up',
  SORT_DOWN: 'Sort down',
  EDIT: 'Edit',
  DELETE: 'Delete',
  FEED: 'Feed',
};
